//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string idUsuario { get; set; }
        public string identificacion { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string dir { get; set; }
        public string idMunic { get; set; }
        public string tel { get; set; }
        public string cel { get; set; }
        public string password { get; set; }
        public Nullable<int> tipo { get; set; }
    }
}
